name = "ifaqai"
compatibility_date = "2025-10-31"
pages_build_output_dir = "build"

[site]
bucket = "./build"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTOR_INDEX"
index_name = "neocortex"

[[d1_databases]]
binding = "DB"
database_name = "hippocampus"
database_id = "c8ed78d0-79ae-45ff-9e12-5cd102aca9cb"